matrix:
  include:
    # Job 1) Run analyzer
    - os: linux
      env:
        - SHARD=Analyze
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone --single-branch --branch stable https://github.com/flutter/flutter.git $HOME/flutter
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        - flutter analyze
    # Job 2) Build the Android axample application (.apk)
    - os: linux
      env:
        - SHARD="Build example apks"
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
            - libstdc++6
            - fonts-droid
      before_script:
        - ./scripts/before_build_apks.sh
        - export ANDROID_HOME=$HOME/android-sdk
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - cd ./example
        - flutter build apk
    # Job 3) Build the iOS example Applications (.ipa)
    - os: osx
      env:
        - SHARD="Build example ipas"
      language: generic
      osx_image: xcode10.1
      before_script:
        - ./scripts/before_build_ipas.sh
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - cd ./example
        - flutter build ios --no-codesign
cache:
  directories:
    - $HOME/.pub-cache
