name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 5.1.0+2
homepage: https://github.com/baseflowit/flutter-permission-handler

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin
      ios:
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  permission_handler_platform_interface: ^2.0.2

dev_dependencies:
  effective_dart: ^1.2.1
  plugin_platform_interface: ^1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
