name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 6.1.3
homepage: https://github.com/baseflowit/flutter-permission-handler

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin
      ios:
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  permission_handler_platform_interface: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  effective_dart: ^1.3.0
  plugin_platform_interface: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.8"
